export const themes = {
  dashboardPro: {
    name: "Dashboard Pro",
    preview: "bg-slate-900",
    sidebar: "bg-slate-900 text-white",
    sidebarItem: "hover:bg-white/10 rounded-lg",
    sidebarActive: () => "bg-white/15 text-white ring-1 ring-white/20",
    sidebarInactive: "text-slate-400 hover:bg-white/[0.06] hover:text-slate-200",
    sidebarTitle: "text-white",
    main: "bg-gray-50",
    card: "bg-white rounded-xl shadow-sm border border-gray-200/60",
    cardHover: "hover:shadow-md hover:-translate-y-px transition-all duration-200",
    input: "bg-white border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 rounded-lg outline-none",
    btnPrimary: "bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors",
    btnSecondary: "bg-gray-100 text-gray-600 rounded-lg hover:bg-gray-200 transition-colors",
    btnDanger: "bg-rose-500 text-white rounded-lg hover:bg-rose-600 transition-colors",
    btnDark: "bg-gray-800 text-white rounded-lg hover:bg-gray-900 transition-colors",
    table: "bg-white rounded-xl shadow-sm border border-gray-200/60 overflow-hidden",
    tableHeader: "bg-gray-50 text-gray-500 border-b border-gray-200",
    tableRow: "hover:bg-gray-50/80 transition-colors",
    badge: {
      active: "bg-emerald-50 text-emerald-700 ring-1 ring-emerald-600/20",
      inactive: "bg-rose-50 text-rose-700 ring-1 ring-rose-600/20",
      info: "bg-blue-50 text-blue-700 ring-1 ring-blue-600/20",
      closed: "bg-gray-100 text-gray-500",
    },
    modal: "bg-white rounded-2xl shadow-2xl",
    overlay: "bg-black/40 backdrop-blur-sm",
    text: { primary: "text-gray-900", secondary: "text-gray-500", muted: "text-gray-400" },
    tabContainer: "bg-gray-100 p-1 rounded-lg",
    tabActive: "bg-white text-gray-900 shadow-sm",
    tabInactive: "text-gray-500 hover:text-gray-700",
    divider: "border-gray-200",
    dropdownBg: "bg-white border border-gray-200 shadow-xl",
    regionCard: "bg-white border border-gray-200 shadow-sm",
    regionCardHeader: "bg-gray-50 border-b border-gray-200",
    emptyState: "bg-white border border-dashed border-gray-300",
    statCard: (color) => `bg-${color}-50 border border-${color}-100`,
    accent: "blue",
  },

  modernMinimal: {
    name: "Minimal",
    preview: "bg-white border-2 border-gray-300",
    sidebar: "bg-white border-r border-gray-200 text-gray-800",
    sidebarItem: "hover:bg-gray-100 rounded-lg",
    sidebarActive: () => "bg-gray-900 text-white",
    sidebarInactive: "text-gray-400 hover:bg-gray-50 hover:text-gray-600",
    sidebarTitle: "text-gray-900",
    main: "bg-white",
    card: "bg-white rounded-lg border border-gray-200",
    cardHover: "hover:border-gray-300 transition-all duration-200",
    input: "bg-white border border-gray-300 focus:border-gray-900 focus:ring-1 focus:ring-gray-900/10 rounded-lg outline-none",
    btnPrimary: "bg-gray-900 text-white rounded-lg hover:bg-gray-800 transition-colors",
    btnSecondary: "bg-white text-gray-600 rounded-lg border border-gray-300 hover:bg-gray-50 transition-colors",
    btnDanger: "text-rose-600 rounded-lg border border-rose-200 hover:bg-rose-50 transition-colors",
    btnDark: "bg-gray-900 text-white rounded-lg hover:bg-gray-800 transition-colors",
    table: "bg-white rounded-lg border border-gray-200 overflow-hidden",
    tableHeader: "bg-gray-50 text-gray-500 border-b border-gray-200",
    tableRow: "hover:bg-gray-50 transition-colors",
    badge: {
      active: "text-emerald-700 ring-1 ring-emerald-200 bg-transparent",
      inactive: "text-rose-700 ring-1 ring-rose-200 bg-transparent",
      info: "text-gray-600 ring-1 ring-gray-200 bg-transparent",
      closed: "text-gray-400 ring-1 ring-gray-200 bg-transparent",
    },
    modal: "bg-white rounded-xl shadow-xl border border-gray-200",
    overlay: "bg-black/30 backdrop-blur-[2px]",
    text: { primary: "text-gray-900", secondary: "text-gray-500", muted: "text-gray-400" },
    tabContainer: "border border-gray-200 p-0.5 rounded-lg bg-gray-50",
    tabActive: "bg-white text-gray-900 shadow-sm",
    tabInactive: "text-gray-400 hover:text-gray-600",
    divider: "border-gray-200",
    dropdownBg: "bg-white border border-gray-200 shadow-lg",
    regionCard: "bg-white border border-gray-200",
    regionCardHeader: "border-b border-gray-200",
    emptyState: "border border-gray-200",
    statCard: () => "bg-gray-50 border border-gray-200",
    accent: "gray",
  },

  glassmorphism: {
    name: "Glass",
    preview: "bg-gradient-to-br from-indigo-400 to-purple-400",
    sidebar: "bg-slate-900/80 backdrop-blur-xl text-white border-r border-white/10",
    sidebarItem: "hover:bg-white/10 rounded-lg",
    sidebarActive: () => "bg-white/15 text-white backdrop-blur-sm ring-1 ring-white/20",
    sidebarInactive: "text-white/50 hover:bg-white/[0.06] hover:text-white/80",
    sidebarTitle: "text-white",
    main: "glass-bg",
    card: "bg-white/60 backdrop-blur-xl rounded-xl shadow-sm border border-white/80",
    cardHover: "hover:bg-white/70 hover:shadow-md hover:-translate-y-px transition-all duration-200",
    input: "bg-white/60 backdrop-blur-sm border border-gray-200/60 focus:border-purple-400 focus:ring-2 focus:ring-purple-400/20 rounded-lg outline-none",
    btnPrimary: "bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-lg shadow-sm hover:shadow-md transition-all",
    btnSecondary: "bg-white/60 backdrop-blur-sm text-gray-600 rounded-lg border border-white/80 hover:bg-white/80 transition-all",
    btnDanger: "bg-gradient-to-r from-rose-500 to-pink-500 text-white rounded-lg transition-all",
    btnDark: "bg-gray-800/80 backdrop-blur-sm text-white rounded-lg hover:bg-gray-900/80 transition-all",
    table: "bg-white/50 backdrop-blur-xl rounded-xl border border-white/70 overflow-hidden",
    tableHeader: "bg-white/30 text-gray-500 border-b border-white/40",
    tableRow: "hover:bg-white/40 transition-colors",
    badge: {
      active: "bg-emerald-50/70 text-emerald-700 ring-1 ring-emerald-200/60",
      inactive: "bg-rose-50/70 text-rose-700 ring-1 ring-rose-200/60",
      info: "bg-blue-50/70 text-blue-700 ring-1 ring-blue-200/60",
      closed: "bg-gray-100/70 text-gray-500",
    },
    modal: "bg-white/80 backdrop-blur-2xl rounded-2xl shadow-2xl border border-white/60",
    overlay: "bg-black/30 backdrop-blur-md",
    text: { primary: "text-gray-900", secondary: "text-gray-500", muted: "text-gray-400" },
    tabContainer: "bg-white/30 backdrop-blur-sm p-1 rounded-lg border border-white/40",
    tabActive: "bg-white/70 backdrop-blur-sm text-purple-700 shadow-sm",
    tabInactive: "text-gray-500 hover:text-gray-700",
    divider: "border-white/40",
    dropdownBg: "bg-white/80 backdrop-blur-xl border border-white/60 shadow-xl",
    regionCard: "bg-white/50 backdrop-blur-xl border border-white/60",
    regionCardHeader: "bg-white/30 border-b border-white/40",
    emptyState: "bg-white/30 backdrop-blur-sm border border-dashed border-white/50",
    statCard: () => "bg-white/40 backdrop-blur-sm border border-white/50",
    accent: "purple",
  },
};

export const themeKeys = Object.keys(themes);
export default themes;
